/* ============================================================
   CGAP · blog-data.js
   window.BLOG_TIPS: 20 tips de la sección "Blog & tips" de nosotros.html.
   Mismo contenido que las 20 fichas pages/blog-<slug>.html (generadas a
   partir de este mismo set, ver CLAUDE.md) — si se edita un tip acá,
   también hay que regenerar su ficha individual.
   ============================================================ */
window.BLOG_TIPS = [
  { slug: "cada-cuanto-control-ginecologico", categoria: "ginecologia",
    titulo: "¿Cada cuánto hacer un control ginecológico?",
    what: "Cuándo ir al ginecólogo, qué se evalúa en la consulta y por qué es importante aunque no tengas síntomas.",
    quick: "El control ginecológico es una instancia clave para prevenir, detectar cambios a tiempo y resolver dudas sobre tu salud íntima. La frecuencia puede variar según edad, antecedentes, síntomas y criterio médico.",
    ctaHref: "https://wa.me/5493515079642?text=Hola%2C%20quisiera%20solicitar%20un%20turno%20de%20control%20ginecol%C3%B3gico.",
    ctaLabel: "Solicitar turno", ctaWa: true, featured: true },
  { slug: "pap-y-videocolposcopia-diferencias", categoria: "ginecologia",
    titulo: "PAP y videocolposcopía: diferencias y cuándo hacerlos",
    what: "Qué diferencia al PAP de la videocolposcopía, para qué sirve cada estudio y por qué pueden complementarse.",
    quick: "El PAP analiza células del cuello uterino, mientras que la videocolposcopía permite observarlo con aumento para detectar posibles alteraciones. Ambos son simples y muy importantes.",
    ctaHref: "https://wa.me/5493515079642?text=Hola%2C%20quisiera%20solicitar%20un%20turno%20para%20PAP%20o%20videocolposcop%C3%ADa.",
    ctaLabel: "Solicitar turno", ctaWa: true, featured: true },
  { slug: "hpv-sintomas-controles-cuando-consultar", categoria: "ginecologia",
    titulo: "HPV: síntomas, controles y cuándo consultar",
    what: "Qué es el HPV, por qué puede no dar síntomas y qué controles ayudan a detectarlo y hacer seguimiento.",
    quick: "El HPV es muy frecuente y muchas veces no presenta síntomas. Los controles ginecológicos regulares son fundamentales para la prevención y el seguimiento.",
    ctaHref: "https://wa.me/5493515079642?text=Hola%2C%20quisiera%20consultar%20sobre%20HPV%20y%20controles.",
    ctaLabel: "Pedir consulta", ctaWa: true, featured: true },
  { slug: "flujo-vaginal-cuando-es-normal", categoria: "ginecologia",
    titulo: "Flujo vaginal: cuándo es normal y cuándo consultar",
    what: "Qué cambios en el flujo conviene observar y en qué situaciones es recomendable una consulta ginecológica.",
    quick: "El flujo vaginal puede variar durante el ciclo, pero si aparece olor fuerte, picazón, ardor, dolor o cambio marcado de color, conviene consultar.",
    ctaHref: "https://wa.me/5493515079642?text=Hola%2C%20quisiera%20solicitar%20una%20consulta%20ginecol%C3%B3gica.",
    ctaLabel: "Solicitar turno", ctaWa: true, featured: false },
  { slug: "dolor-menstrual-fuerte-causas-alerta", categoria: "ginecologia",
    titulo: "Dolor menstrual fuerte: causas y señales de alerta",
    what: "Cuándo el dolor menstrual puede ser esperable, cuándo deja de ser normal y qué señales indican consultar.",
    quick: "Un poco de molestia menstrual puede ser frecuente, pero el dolor intenso, incapacitante o que empeora con el tiempo no debería naturalizarse.",
    ctaHref: "https://wa.me/5493515079642?text=Hola%2C%20quisiera%20consultar%20por%20dolor%20menstrual.",
    ctaLabel: "Pedir consulta", ctaWa: true, featured: false },
  { slug: "circuito-ginecologico-que-incluye", categoria: "ginecologia",
    titulo: "Circuito ginecológico: qué estudios incluye y cómo funciona",
    what: "Qué es un circuito ginecológico, qué estudios puede incluir y por qué permite un control más organizado.",
    quick: "El circuito ginecológico es una forma práctica de realizar consulta, estudios y seguimiento dentro de un recorrido coordinado, según la indicación médica de cada paciente.",
    ctaHref: "circuito.html",
    ctaLabel: "Conocer el circuito", ctaWa: false, featured: false },

  { slug: "control-de-lunares-dermatologia", categoria: "dermatologia",
    titulo: "Control de lunares: cuándo consultar con dermatología",
    what: "Qué cambios en los lunares conviene observar y por qué el control periódico de la piel es importante.",
    quick: "Si un lunar cambia de forma, color, tamaño, bordes, pica, sangra o aparece una lesión nueva que te llama la atención, conviene hacer una consulta dermatológica.",
    ctaHref: "https://wa.me/5493515079642?text=Hola%2C%20quisiera%20solicitar%20un%20turno%20dermatol%C3%B3gico%20para%20control%20de%20lunares.",
    ctaLabel: "Solicitar turno", ctaWa: true, featured: false },
  { slug: "manchas-en-la-cara-causas-tratamientos", categoria: "dermatologia",
    titulo: "Manchas en la cara: causas y tratamientos posibles",
    what: "Por qué pueden aparecer manchas en la cara, qué factores las empeoran y por qué evaluarlas antes de tratar.",
    quick: "Las manchas pueden aparecer por sol, cambios hormonales, acné, embarazo o anticonceptivos. No todos los tratamientos sirven para todos los tipos de manchas.",
    ctaHref: "https://wa.me/5493515079642?text=Hola%2C%20quisiera%20consultar%20por%20manchas%20en%20la%20cara.",
    ctaLabel: "Consultar por manchas", ctaWa: true, featured: false },
  { slug: "acne-adulto-despues-de-los-25", categoria: "dermatologia",
    titulo: "Acné adulto: por qué aparece después de los 25",
    what: "Por qué puede aparecer acné en adultos, qué factores influyen y cuándo consultar con dermatología.",
    quick: "El acné adulto es frecuente y puede estar relacionado con hormonas, estrés, cosméticos, genética, alimentación, ciclo menstrual u otras condiciones médicas.",
    ctaHref: "https://wa.me/5493515079642?text=Hola%2C%20quisiera%20consultar%20por%20acn%C3%A9%20adulto.",
    ctaLabel: "Pedir consulta", ctaWa: true, featured: false },
  { slug: "piel-sensible-cuidados-basicos", categoria: "dermatologia",
    titulo: "Piel sensible: cuidados básicos y cuándo consultar",
    what: "Cómo cuidar una piel sensible, qué hábitos pueden irritarla y cuándo conviene consultar un profesional.",
    quick: "La piel sensible puede reaccionar con ardor, enrojecimiento, picazón o tirantez. Una rutina simple y bien indicada puede ayudar más que usar muchos productos.",
    ctaHref: "https://wa.me/5493515079642?text=Hola%2C%20quisiera%20consultar%20por%20piel%20sensible.",
    ctaLabel: "Consultar por mi piel", ctaWa: true, featured: false },

  { slug: "depilacion-definitiva-como-prepararte", categoria: "estetica",
    titulo: "Depilación definitiva: cómo prepararte para tu sesión",
    what: "Cómo prepararte para una sesión de depilación definitiva y qué cuidados tener antes del tratamiento.",
    quick: "Antes de una sesión de depilación definitiva, suele recomendarse evitar el sol, no arrancar el pelo de raíz y seguir las indicaciones del equipo profesional.",
    ctaHref: "https://api.whatsapp.com/message/W6ZS5FUMO4O4F1?autoload=1&app_absent=0&utm_source=ig",
    ctaLabel: "Consultar por depilación", ctaWa: true, featured: false },
  { slug: "cuantas-sesiones-depilacion-definitiva", categoria: "estetica",
    titulo: "¿Cuántas sesiones de depilación definitiva necesito?",
    what: "Cuántas sesiones suelen necesitarse, qué factores influyen en los resultados y por qué importa la constancia.",
    quick: "La cantidad de sesiones varía según la zona, el tipo de piel, el tipo de pelo, factores hormonales y la respuesta individual al tratamiento.",
    ctaHref: "https://api.whatsapp.com/message/W6ZS5FUMO4O4F1?autoload=1&app_absent=0&utm_source=ig",
    ctaLabel: "Evaluar mi caso", ctaWa: true, featured: false },
  { slug: "luz-pulsada-para-que-sirve", categoria: "estetica",
    titulo: "Luz pulsada: para qué sirve y cuándo puede ayudar",
    what: "Qué es la luz pulsada, en qué casos puede indicarse y por qué es importante una evaluación previa.",
    quick: "La luz pulsada (IPL) puede utilizarse para manchas, rojeces, textura irregular o signos de fotoenvejecimiento, según evaluación profesional.",
    ctaHref: "https://api.whatsapp.com/message/W6ZS5FUMO4O4F1?autoload=1&app_absent=0&utm_source=ig",
    ctaLabel: "Consultar por luz pulsada", ctaWa: true, featured: false },
  { slug: "laser-co2-que-es-para-que-sirve", categoria: "estetica",
    titulo: "Láser CO₂: qué es, para qué sirve y cuidados posteriores",
    what: "Qué es el láser CO₂, en qué casos puede utilizarse y qué cuidados requiere antes y después del procedimiento.",
    quick: "El láser CO₂ puede indicarse en casos de cicatrices, textura irregular, lesiones específicas o rejuvenecimiento cutáneo, siempre según evaluación profesional.",
    ctaHref: "https://api.whatsapp.com/message/W6ZS5FUMO4O4F1?autoload=1&app_absent=0&utm_source=ig",
    ctaLabel: "Consultar por láser CO₂", ctaWa: true, featured: false },

  { slug: "comer-mejor-sin-dieta-extrema", categoria: "nutricion",
    titulo: "Comer mejor sin hacer una dieta extrema",
    what: "Cómo empezar a mejorar la alimentación sin restricciones extremas y qué hábitos simples pueden ayudarte.",
    quick: "Comer mejor no tiene que ser sinónimo de pasar hambre o prohibirse todo. Muchas veces, el primer paso es ordenar hábitos y armar un plan posible para tu rutina.",
    ctaHref: "https://wa.me/5493515079642?text=Hola%2C%20quisiera%20solicitar%20un%20turno%20con%20nutrici%C3%B3n.",
    ctaLabel: "Solicitar turno", ctaWa: true, featured: false },
  { slug: "hambre-constante-causas", categoria: "nutricion",
    titulo: "Hambre constante: posibles causas y cómo abordarla",
    what: "Por qué podés sentir hambre todo el día, qué hábitos pueden influir y cuándo consultar con un profesional.",
    quick: "Tener hambre todo el día no siempre es falta de voluntad. Puede relacionarse con comidas poco completas, mal descanso, estrés, ansiedad, hábitos desordenados o factores hormonales.",
    ctaHref: "https://wa.me/5493515079642?text=Hola%2C%20quisiera%20consultar%20con%20nutrici%C3%B3n.",
    ctaLabel: "Ordenar mi alimentación", ctaWa: true, featured: false },
  { slug: "organizar-comidas-poco-tiempo", categoria: "nutricion",
    titulo: "Cómo organizar tus comidas si tenés poco tiempo",
    what: "Estrategias prácticas para comer mejor cuando la rutina está llena y el tiempo es escaso.",
    quick: "La clave no siempre es cocinar más, sino decidir mejor antes de tener hambre. Una mínima organización puede ayudarte a comer mejor durante la semana.",
    ctaHref: "https://wa.me/5493515079642?text=Hola%2C%20quisiera%20solicitar%20un%20turno%20con%20nutrici%C3%B3n.",
    ctaLabel: "Solicitar turno con nutrición", ctaWa: true, featured: false },

  { slug: "tiroides-sintomas-frecuentes", categoria: "endocrinologia",
    titulo: "Tiroides: síntomas frecuentes y cuándo consultar",
    what: "Qué síntomas pueden estar relacionados con la tiroides y por qué es importante evaluar el cuadro completo.",
    quick: "La tiroides puede influir en energía, peso, piel, pelo, ánimo, ciclo menstrual y metabolismo. Si hay síntomas persistentes, conviene consultar.",
    ctaHref: "https://wa.me/5493515079642?text=Hola%2C%20quisiera%20consultar%20con%20endocrinolog%C3%ADa.",
    ctaLabel: "Consultar con endocrinología", ctaWa: true, featured: false },
  { slug: "resistencia-a-la-insulina", categoria: "endocrinologia",
    titulo: "Resistencia a la insulina: qué significa y cuándo evaluarla",
    what: "Qué es la resistencia a la insulina, qué señales pueden aparecer y cómo puede abordarse de forma integral.",
    quick: "La resistencia a la insulina ocurre cuando el cuerpo necesita producir más insulina para lograr el mismo efecto. Detectarla a tiempo puede ayudar a prevenir complicaciones.",
    ctaHref: "https://wa.me/5493515079642?text=Hola%2C%20quisiera%20consultar%20sobre%20resistencia%20a%20la%20insulina.",
    ctaLabel: "Evaluar mi metabolismo", ctaWa: true, featured: false },
  { slug: "sindrome-ovario-poliquistico", categoria: "endocrinologia",
    titulo: "Síndrome de ovario poliquístico: síntomas y seguimiento",
    what: "Qué es el SOP, qué síntomas puede generar y por qué muchas veces requiere un abordaje integral.",
    quick: "El síndrome de ovario poliquístico puede afectar el ciclo menstrual, la piel, el metabolismo y las hormonas. No todas las personas presentan los mismos síntomas.",
    ctaHref: "https://wa.me/5493515079642?text=Hola%2C%20quisiera%20consultar%20sobre%20SOP.",
    ctaLabel: "Reservar consulta", ctaWa: true, featured: false },
];
